// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjpf_wW0oUBq8pzfN3eDyngiO8csm9_zQ',
    appId: '1:793123783270:web:f57d7da11f66b9631da3a7',
    messagingSenderId: '793123783270',
    projectId: 'attendanc',
    authDomain: 'attendanc.firebaseapp.com',
    storageBucket: 'attendanc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVnRw20WmEbiBPhODLSF5xeNDLaH67Bh8',
    appId: '1:793123783270:android:afd48584fd0538621da3a7',
    messagingSenderId: '793123783270',
    projectId: 'attendanc',
    storageBucket: 'attendanc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9645lQ7w2ONXEZVXaEOwnxjAbEZNkXA',
    appId: '1:793123783270:ios:cfa1e12d739f29c71da3a7',
    messagingSenderId: '793123783270',
    projectId: 'attendanc',
    storageBucket: 'attendanc.appspot.com',
    iosClientId: '793123783270-kgc6iabg46qd8uvqnllrsnhp828cd647.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH9645lQ7w2ONXEZVXaEOwnxjAbEZNkXA',
    appId: '1:793123783270:ios:cfa1e12d739f29c71da3a7',
    messagingSenderId: '793123783270',
    projectId: 'attendanc',
    storageBucket: 'attendanc.appspot.com',
    iosClientId: '793123783270-kgc6iabg46qd8uvqnllrsnhp828cd647.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
